// <auto-generated />
using System;
using JSCHUB.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JSCHUB.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReminderDbContext))]
    [Migration("20251223084247_AddPromptsModule")]
    partial class AddPromptsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JSCHUB.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("OccurrenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReminderItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TriggerAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReminderItemId");

                    b.HasIndex("Severity");

                    b.HasIndex("State");

                    b.HasIndex("TriggerAt");

                    b.HasIndex("ReminderItemId", "OccurrenceAt");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.EnlaceProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ModificadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("Tipo");

                    b.HasIndex("ProyectoId", "Orden");

                    b.ToTable("enlaces_proyecto", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraPago")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Importe")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EUR");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PagadoPorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Concepto");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPago");

                    b.HasIndex("PagadoPorId");

                    b.ToTable("gastos", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.GastoProyecto", b =>
                {
                    b.Property<Guid>("GastoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.HasKey("GastoId", "ProyectoId");

                    b.HasIndex("GastoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("gastos_proyectos", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.KanbanColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModificadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Posicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ProyectoId", "Posicion");

                    b.ToTable("kanban_columnas", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.KanbanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AsignadoAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColumnaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("HorasEstimadas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("ModificadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Posicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("ColumnaId");

                    b.HasIndex("Prioridad");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ColumnaId", "Posicion");

                    b.ToTable("kanban_tareas", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreadoEl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificadoEl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModificadoEl");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ToolId");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.PromptTag", b =>
                {
                    b.Property<Guid>("PromptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("PromptId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("prompt_tags", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EnlacePrincipal")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EsGeneral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ModificadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EsGeneral")
                        .IsUnique()
                        .HasDatabaseName("IX_proyectos_EsGeneral_Unique")
                        .HasFilter("\"EsGeneral\" = true");

                    b.HasIndex("Estado");

                    b.HasIndex("ModificadoEl");

                    b.HasIndex("Nombre");

                    b.ToTable("proyectos", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.RecursoProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Etiquetas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ModificadoEl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ModificadoEl");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("Tipo");

                    b.ToTable("recursos_proyecto", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.ReminderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AsignadoAId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CustomIntervalDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastOccurrenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeadTimeDays")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("NextOccurrenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecurrenceFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Madrid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("Category");

                    b.HasIndex("NextOccurrenceAt");

                    b.HasIndex("Status");

                    b.ToTable("reminder_items", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.ReminderItemProyecto", b =>
                {
                    b.Property<Guid>("ReminderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.HasKey("ReminderItemId", "ProyectoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ReminderItemId");

                    b.ToTable("reminder_items_proyectos", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreadoEl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreadoEl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tools", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.UsuarioProyecto", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<string>("AsignadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("UsuarioId", "ProyectoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("Rol");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuarios_proyectos", (string)null);
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Alert", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.ReminderItem", "ReminderItem")
                        .WithMany("Alerts")
                        .HasForeignKey("ReminderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderItem");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.EnlaceProyecto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Enlaces")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Usuario", "PagadoPor")
                        .WithMany("Gastos")
                        .HasForeignKey("PagadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PagadoPor");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.GastoProyecto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Gasto", "Gasto")
                        .WithMany("GastosProyecto")
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("GastosProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gasto");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.KanbanColumn", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.KanbanTask", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Usuario", "AsignadoA")
                        .WithMany()
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JSCHUB.Domain.Entities.KanbanColumn", "Columna")
                        .WithMany("Tareas")
                        .HasForeignKey("ColumnaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Columna");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Prompt", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Usuario", "CreatedByUser")
                        .WithMany("PromptsCreados")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JSCHUB.Domain.Entities.Tool", "Tool")
                        .WithMany("Prompts")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Proyecto");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.PromptTag", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Prompt", "Prompt")
                        .WithMany("PromptTags")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.Tag", "Tag")
                        .WithMany("PromptTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.RecursoProyecto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Recursos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.ReminderItem", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Usuario", "AsignadoA")
                        .WithMany("ReminderItemsAsignados")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AsignadoA");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.ReminderItemProyecto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("ReminderItemsProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.ReminderItem", "ReminderItem")
                        .WithMany("ReminderItemsProyecto")
                        .HasForeignKey("ReminderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("ReminderItem");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.UsuarioProyecto", b =>
                {
                    b.HasOne("JSCHUB.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("UsuariosProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JSCHUB.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioProyectos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Gasto", b =>
                {
                    b.Navigation("GastosProyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.KanbanColumn", b =>
                {
                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Prompt", b =>
                {
                    b.Navigation("PromptTags");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("Enlaces");

                    b.Navigation("GastosProyecto");

                    b.Navigation("Recursos");

                    b.Navigation("ReminderItemsProyecto");

                    b.Navigation("UsuariosProyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.ReminderItem", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ReminderItemsProyecto");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Tag", b =>
                {
                    b.Navigation("PromptTags");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Tool", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("JSCHUB.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("PromptsCreados");

                    b.Navigation("ReminderItemsAsignados");

                    b.Navigation("UsuarioProyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
